<?php

namespace Database\Seeders;

use App\Models\Cargo;
use Illuminate\Database\Seeder;

class CargoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cargos = [
            ['nome' => 'Auxiliar Administrativo', 'descricao' => 'Responsável por dar suporte nas rotinas administrativas, como organização de documentos, controle de correspondências e atendimento ao público.'],
            ['nome' => 'Assistente Administrativo', 'descricao' => 'Atua no apoio à gestão administrativa, realizando atividades como controle de arquivos e agendamentos.'],
            ['nome' => 'Secretária Executiva', 'descricao' => 'Auxilia executivos, organizando agendas, correspondências e viagens.'],
            ['nome' => 'Recepcionista', 'descricao' => 'Recebe visitantes, atende chamadas e direciona solicitações aos departamentos.'],
            ['nome' => 'Analista de RH', 'descricao' => 'Responsável por recrutamento, seleção e administração de pessoal.'],
            ['nome' => 'Operador de Telemarketing', 'descricao' => 'Realiza atendimento ao cliente via telefone para venda ou suporte de produtos e serviços.'],
            ['nome' => 'Vendedor Interno', 'descricao' => 'Atua em vendas dentro de estabelecimentos comerciais, auxiliando clientes com informações sobre produtos.'],
            ['nome' => 'Vendedor Externo', 'descricao' => 'Realiza vendas fora do ambiente da empresa, visitando clientes e estabelecendo relações comerciais.'],
            ['nome' => 'Gerente de Loja', 'descricao' => 'Supervisiona a equipe e gerencia o desempenho de uma loja, garantindo metas de vendas.'],
            ['nome' => 'Estoquista', 'descricao' => 'Responsável pelo controle e organização do estoque de produtos.'],
            ['nome' => 'Assistente de Logística', 'descricao' => 'Dá suporte na organização e monitoramento de transporte e armazenamento de mercadorias.'],
            ['nome' => 'Motorista', 'descricao' => 'Realiza o transporte de pessoas ou cargas em veículos.'],
            ['nome' => 'Auxiliar de Produção', 'descricao' => 'Trabalha no chão de fábrica auxiliando na linha de produção de mercadorias.'],
            ['nome' => 'Operador de Máquinas', 'descricao' => 'Opera máquinas industriais em processos de fabricação.'],
            ['nome' => 'Técnico em Segurança do Trabalho', 'descricao' => 'Implementa e inspeciona medidas de segurança no ambiente de trabalho.'],
            ['nome' => 'Supervisor de Produção', 'descricao' => 'Gerencia equipes de produção para garantir a eficiência e qualidade dos processos.'],
            ['nome' => 'Assistente Financeiro', 'descricao' => 'Auxilia no controle e planejamento financeiro da empresa, realizando atividades como contas a pagar e receber.'],
            ['nome' => 'Analista Financeiro', 'descricao' => 'Análise de fluxo de caixa, investimentos e orçamentos, buscando otimização dos recursos.'],
            ['nome' => 'Auxiliar Contábil', 'descricao' => 'Dá suporte na classificação e conciliação contábil, bem como no fechamento de balanços.'],
            ['nome' => 'Contador', 'descricao' => 'Responsável pela escrituração contábil, apuração de impostos e elaboração de balanços.'],
            ['nome' => 'Supervisor de Vendas', 'descricao' => 'Coordena equipes de vendas, estabelecendo metas e acompanhando resultados.'],
            ['nome' => 'Coordenador de Marketing', 'descricao' => 'Desenvolve estratégias de marketing e coordena campanhas publicitárias.'],
            ['nome' => 'Analista de Marketing', 'descricao' => 'Planeja e executa ações de marketing digital e tradicional, como campanhas e análises de mercado.'],
            ['nome' => 'Designer Gráfico', 'descricao' => 'Cria materiais visuais para campanhas publicitárias, websites, produtos e embalagens.'],
            ['nome' => 'Técnico de Informática', 'descricao' => 'Responsável pela manutenção e suporte de hardware e software em redes de computadores.'],
            ['nome' => 'Programador', 'descricao' => 'Desenvolve sistemas e aplicativos, escrevendo códigos para atender às demandas tecnológicas da empresa.'],
            ['nome' => 'Analista de Sistemas', 'descricao' => 'Realiza a análise de sistemas e softwares para otimização dos processos internos da empresa.'],
            ['nome' => 'Auxiliar de Limpeza', 'descricao' => 'Responsável pela limpeza e conservação de ambientes.'],
            ['nome' => 'Zelador', 'descricao' => 'Cuida da segurança e manutenção de prédios e áreas comuns.'],
            ['nome' => 'Porteiro', 'descricao' => 'Controla a entrada e saída de pessoas em prédios comerciais ou residenciais.'],
            ['nome' => 'Vigilante', 'descricao' => 'Zela pela segurança patrimonial de empresas e condomínios.'],
            ['nome' => 'Auxiliar de Cozinha', 'descricao' => 'Ajuda na preparação de refeições e na limpeza da cozinha.'],
            ['nome' => 'Cozinheiro', 'descricao' => 'Prepara refeições em restaurantes, bares ou cozinhas industriais.'],
            ['nome' => 'Garçom', 'descricao' => 'Atende clientes em restaurantes, servindo alimentos e bebidas.'],
            ['nome' => 'Auxiliar de Serviços Gerais', 'descricao' => 'Executa serviços gerais como manutenção, limpeza e pequenos reparos.'],
            ['nome' => 'Supervisor de Logística', 'descricao' => 'Coordena processos de distribuição e transporte de mercadorias.'],
            ['nome' => 'Engenheiro Civil', 'descricao' => 'Planeja, supervisiona e executa projetos de construção civil.'],
            ['nome' => 'Eletricista', 'descricao' => 'Realiza instalações e manutenções elétricas em residências, indústrias e comércios.'],
            ['nome' => 'Mecânico de Manutenção', 'descricao' => 'Realiza a manutenção preventiva e corretiva de máquinas e equipamentos.'],
            ['nome' => 'Operador de Caixa', 'descricao' => 'Opera o caixa de estabelecimentos comerciais, registrando e processando pagamentos.'],
            ['nome' => 'Auxiliar de Almoxarifado', 'descricao' => 'Organiza e controla o estoque de materiais, recebendo e distribuindo mercadorias.'],
            ['nome' => 'Almoxarife', 'descricao' => 'Gerencia o estoque de mercadorias e materiais, controlando entradas e saídas.'],
            ['nome' => 'Carregador', 'descricao' => 'Responsável por carregar e descarregar mercadorias.'],
            ['nome' => 'Pedreiro', 'descricao' => 'Trabalha na construção de edificações, realizando obras de alvenaria e acabamento.'],
            ['nome' => 'Servente de Obras', 'descricao' => 'Apoia os pedreiros e mestres de obras em construções civis.'],
            ['nome' => 'Encanador', 'descricao' => 'Instala e repara sistemas de encanamento e esgoto.'],
            ['nome' => 'Pintor', 'descricao' => 'Realiza pinturas de paredes, edifícios e móveis.'],
            ['nome' => 'Jardineiro', 'descricao' => 'Cuida da manutenção de jardins, podas e plantio de flores e árvores.'],
            ['nome' => 'Faxineiro', 'descricao' => 'Executa a limpeza de espaços comerciais e residenciais.'],
            ['nome' => 'Supervisor de Atendimento', 'descricao' => 'Coordena equipes de atendimento ao cliente, garantindo a eficiência nos serviços prestados.'],
            ['nome' => 'Auxiliar de Escritório', 'descricao' => 'Realiza atividades de suporte administrativo, como digitalização e organização de documentos.'],
            ['nome' => 'Técnico em Enfermagem', 'descricao' => 'Presta cuidados básicos de saúde sob a supervisão de enfermeiros e médicos.'],
            ['nome' => 'Enfermeiro', 'descricao' => 'Realiza atendimentos de saúde, aplica medicações e orienta pacientes.'],
            ['nome' => 'Recepcionista de Consultório', 'descricao' => 'Recebe pacientes, agenda consultas e organiza documentos médicos.'],
            ['nome' => 'Balconista', 'descricao' => 'Atende clientes em balcões de atendimento de lojas, padarias ou farmácias.'],
            ['nome' => 'Atendente de Farmácia', 'descricao' => 'Atende clientes em farmácias, orientando sobre medicamentos e processando compras.'],
            ['nome' => 'Técnico em Laboratório', 'descricao' => 'Realiza exames laboratoriais e opera equipamentos médicos.'],
            ['nome' => 'Supervisor de Call Center', 'descricao' => 'Gerencia equipes de telemarketing e atendimento telefônico.'],
            ['nome' => 'Controlador de Acesso', 'descricao' => 'Fiscaliza a entrada e saída de pessoas em locais com segurança controlada.'],
            ['nome' => 'Auxiliar de Transporte', 'descricao' => 'Ajuda no transporte de mercadorias e na logística de cargas.'],
            ['nome' => 'Técnico de Manutenção', 'descricao' => 'Faz manutenções preventivas e corretivas em máquinas e sistemas operacionais.'],
            ['nome' => 'Auxiliar de Padeiro', 'descricao' => 'Ajuda no preparo de pães e doces em padarias.'],
            ['nome' => 'Padeiro', 'descricao' => 'Prepara pães e outros produtos de panificação.'],
            ['nome' => 'Conferente de Mercadorias', 'descricao' => 'Confere o recebimento e envio de mercadorias no estoque.'],
            ['nome' => 'Cobrador de Ônibus', 'descricao' => 'Recebe e controla o pagamento de passagens em transporte coletivo.'],
            ['nome' => 'Fiscal de Loja', 'descricao' => 'Monitora o comportamento dos clientes em lojas, prevenindo furtos e incidentes.'],
            ['nome' => 'Auxiliar de Carga e Descarga', 'descricao' => 'Ajuda no carregamento e descarregamento de mercadorias de caminhões e outros veículos de transporte.'],
            ['nome' => 'Montador de Móveis', 'descricao' => 'Monta móveis em lojas ou residências, seguindo manuais de instruções.'],
            ['nome' => 'Atendente de Loja', 'descricao' => 'Auxilia clientes em lojas com informações sobre produtos e serviços.'],
            ['nome' => 'Chapeiro', 'descricao' => 'Prepara alimentos como lanches e refeições rápidas em chapas.'],
            ['nome' => 'Técnico em Telecomunicações', 'descricao' => 'Faz a instalação e manutenção de sistemas de telecomunicações, como internet e telefonia.'],
            ['nome' => 'Pizzaiolo', 'descricao' => 'Prepara pizzas, gerenciando massas, recheios e forno.'],
            ['nome' => 'Operador de Empilhadeira', 'descricao' => 'Opera empilhadeiras para transporte de materiais em armazéns e fábricas.'],
            ['nome' => 'Auxiliar de Cobrança', 'descricao' => 'Auxilia no controle de pagamentos e na cobrança de débitos de clientes.'],
            ['nome' => 'Atendente de Call Center', 'descricao' => 'Realiza atendimento ao cliente por telefone, oferecendo suporte e informações sobre produtos e serviços.'],
            ['nome' => 'Analista de Crédito', 'descricao' => 'Avalia pedidos de crédito, analisando perfis de clientes e suas capacidades de pagamento.'],
            ['nome' => 'Auxiliar de Expedição', 'descricao' => 'Organiza o envio de mercadorias, controlando prazos e documentação.'],
            ['nome' => 'Ajudante de Pedreiro', 'descricao' => 'Auxilia o pedreiro em obras, carregando materiais e executando serviços simples.'],
            ['nome' => 'Manicure', 'descricao' => 'Realiza cuidados estéticos das unhas, como cortes, esmaltação e hidratação.'],
            ['nome' => 'Cabeleireiro', 'descricao' => 'Cuida da estética dos cabelos, realizando cortes, penteados e tratamentos capilares.'],
            ['nome' => 'Técnico em Edificações', 'descricao' => 'Faz o acompanhamento técnico de obras, garantindo a execução conforme os projetos.'],
            ['nome' => 'Supervisor de Manutenção', 'descricao' => 'Gerencia equipes de manutenção em fábricas ou grandes instalações.'],
            ['nome' => 'Técnico em Eletrônica', 'descricao' => 'Realiza manutenções em equipamentos eletrônicos e sistemas automatizados.'],
            ['nome' => 'Frentista', 'descricao' => 'Atende clientes em postos de combustíveis, abastecendo veículos e verificando condições básicas.'],
            ['nome' => 'Operador de CNC', 'descricao' => 'Opera máquinas CNC para produção de peças a partir de projetos específicos.'],
            ['nome' => 'Caldeireiro', 'descricao' => 'Trabalha na fabricação e manutenção de caldeiras e outros equipamentos industriais.'],
            ['nome' => 'Torneiro Mecânico', 'descricao' => 'Opera tornos mecânicos para fabricar ou reparar peças metálicas.'],
            ['nome' => 'Supervisor de Limpeza', 'descricao' => 'Coordena equipes de limpeza em empresas ou edifícios comerciais.'],
            ['nome' => 'Mecânico de Automóveis', 'descricao' => 'Faz reparos e manutenções em veículos automotores.'],
            ['nome' => 'Auxiliar de Laboratório', 'descricao' => 'Auxilia em atividades laboratoriais, preparando amostras e organizando materiais.'],
            ['nome' => 'Farmacêutico', 'descricao' => 'Dispensa medicamentos e orienta pacientes quanto ao uso correto de medicamentos.'],
            ['nome' => 'Gerente Administrativo', 'descricao' => 'Supervisiona a área administrativa, gerindo equipes e processos burocráticos.'],
            ['nome' => 'Fisioterapeuta', 'descricao' => 'Realiza tratamentos de reabilitação física e motora.'],
            ['nome' => 'Supervisor de Operações', 'descricao' => 'Coordena operações logísticas ou de produção em grandes empresas.'],
        ];

        Cargo::insert($cargos);
    }
}
