// const colors = require("tailwindcss/colors");
// import preset from './vendor/filament/support/tailwind.config.preset';
import defaultTheme from "tailwindcss/defaultTheme";

/** @type {import('tailwindcss').Config} */
export default {
    // presets: [preset],
    darkMode: "selector",
    content: [
        "./app/Filament/**/*.php",
        "./resources/views/filament/**/*.blade.php",
        "./vendor/filament/**/*.blade.php",
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
        "./resources/js/**/*.vue",
        "./node_modules/flowbite/**/*.js",
        "./vendor/kenepa/banner/resources/**/*.php",
    ],

    safelist: [
        "bg-gray-900",
        "bg-gray-900/80",
        "fixed",
        "inset-0",
        "z-[99999]",
        "!z-[99999]",
        "backdrop-blur-sm",
        "flex",
        "items-center",
        "justify-center",
        "bg-white",
        "dark:bg-gray-800",
        "p-10",
        "rounded-2xl",
        "shadow-2xl",
        "text-center",
        "max-w-md",
        "w-full",
        "mx-4",
        "border",
        "border-gray-100",
        "dark:border-gray-700",
        "mb-12",
        "relative",
        "my-4",
        "absolute",
        "text-sm",
        "font-bold",
        "text-primary-600",
        "dark:text-primary-400",
        "animate-spin",
        "h-16",
        "w-16",
        "opacity-25",
        "opacity-75",
        "text-lg",
        "text-gray-900",
        "dark:text-white",
        "mb-2",
        "text-gray-500",
        "dark:text-gray-400",
        "bg-gray-200",
        "rounded-full",
        "h-1.5",
        "dark:bg-gray-700",
        "overflow-hidden",
        "transition-all",
        "duration-300",
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ["Figtree", ...defaultTheme.fontFamily.sans],
            },
            colors: {
                primary: {
                    50: "rgb(var(--color-primary-50) / <alpha-value>)",
                    100: "rgb(var(--color-primary-100) / <alpha-value>)",
                    200: "rgb(var(--color-primary-200) / <alpha-value>)",
                    300: "rgb(var(--color-primary-300) / <alpha-value>)",
                    400: "rgb(var(--color-primary-400) / <alpha-value>)",
                    500: "rgb(var(--color-primary-500) / <alpha-value>)",
                    600: "rgb(var(--color-primary-600) / <alpha-value>)",
                    700: "rgb(var(--color-primary-700) / <alpha-value>)",
                    800: "rgb(var(--color-primary-800) / <alpha-value>)",
                    900: "rgb(var(--color-primary-900) / <alpha-value>)",
                    950: "rgb(var(--color-primary-950) / <alpha-value>)",
                },
            },
        },
    },

    plugins: [require("@tailwindcss/forms")],
};
