import preset from "../../../../vendor/filament/filament/tailwind.config.preset";

export default {
    presets: [preset],
    content: [
        "./app/Filament/**/*.php",
        "./resources/views/filament/**/*.blade.php",
        "./vendor/filament/**/*.blade.php",
        "./resources/views/livewire/**/*.blade.php",
    ],
    safelist: [
        "bg-gray-900",
        "bg-gray-900/80",
        "fixed",
        "inset-0",
        "z-[99999]",
        "!z-[99999]",
        "backdrop-blur-sm",
        "flex",
        "items-center",
        "justify-center",
        "bg-white",
        "dark:bg-gray-800",
        "p-10",
        "rounded-2xl",
        "shadow-2xl",
        "text-center",
        "max-w-md",
        "w-full",
        "mx-4",
        "border",
        "border-gray-100",
        "dark:border-gray-700",
        "mb-12",
        "relative",
        "my-4",
        "absolute",
        "text-sm",
        "font-bold",
        "text-primary-600",
        "dark:text-primary-400",
        "animate-spin",
        "h-16",
        "w-16",
        "opacity-25",
        "opacity-75",
        "text-lg",
        "text-gray-900",
        "dark:text-white",
        "mb-2",
        "text-gray-500",
        "dark:text-gray-400",
        "bg-gray-200",
        "rounded-full",
        "h-1.5",
        "dark:bg-gray-700",
        "overflow-hidden",
        "transition-all",
        "duration-300",
    ],
};
