<?php

namespace App;

use Filament\Support\Contracts\HasLabel;

enum OrgaoExpedidor: string implements HasLabel
{
    case ABNC = 'abnc';
    case AGU = 'agu';
    case ANAC = 'anac';
    case CAER = 'caer';
    case CAU = 'cau';
    case CBM = 'cbm';
    case CFA = 'cfa';
    case CFB = 'cfb';
    case CFBIO = 'cfbio';
    case CFBM = 'cfbm';
    case CFC = 'cfc';
    case CFESS = 'cfess';
    case CFF = 'cff';
    case CFFA = 'cffa';
    case CFM = 'cfm';
    case CFMV = 'cfmv';
    case CFN = 'cfn';
    case CFO = 'cfo';
    case CFP = 'cfp';
    case CFQ = 'cfq';
    case CFT = 'cft';
    case CFTA = 'cfta';
    case CGPI = 'cgpi';
    case CGPMAF = 'cgpmaf';
    case CIPC = 'cipc';
    case CNIG = 'cnig';
    case CNT = 'cnt';
    case CNTV = 'cntv';
    case COFECI = 'cofeci';
    case COFECON = 'cofecon';
    case COFEM = 'cofem';
    case COFEN = 'cofen';
    case COFFITO = 'coffito';
    case COMAER = 'comaer';
    case CONFE = 'confe';
    case CONFEA = 'confea';
    case CONFEF = 'confef';
    case CONFERE = 'confere';
    case CONRE = 'conre';
    case CONRERP = 'conrerp';
    case CORE = 'core';
    case CORECON = 'corecon';
    case COREM = 'corem';
    case COREN = 'coren';
    case CRA = 'cra';
    case CRAS = 'cras';
    case CRB = 'crb';
    case CRBIO = 'crbio';
    case CRBM = 'crbm';
    case CRC = 'crc';
    case CREA = 'crea';
    case CRECI = 'creci';
    case CREF = 'cref';
    case CREFITO = 'crefito';
    case CRESS = 'cress';
    case CRF = 'crf';
    case CRFA = 'crfa';
    case CRM = 'crm';
    case CRMV = 'crmv';
    case CRN = 'crn';
    case CRO = 'cro';
    case CRP = 'crp';
    case CRPRE = 'crpre';
    case CRQ = 'crq';
    case CRT = 'crt';
    case CRTA = 'crta';
    case CTPS = 'ctps';
    case CV = 'cv';
    case DELEMIG = 'delemig';
    case DETRAN = 'detran';
    case DGPC = 'dgpc';
    case DIC = 'dic';
    case DICC = 'dicc';
    case DIREX = 'direx';
    case DPF = 'dpf';
    case DPMAF = 'dpmaf';
    case DPT = 'dpt';
    case DPTC = 'dptc';
    case DREX = 'drex';
    case DRT = 'drt';
    case EB = 'eb';
    case FAB = 'fab';
    case FENAJ = 'fenaj';
    case FGTS = 'fgts';
    case FIPE = 'fipe';
    case FLS = 'fls';
    case FUNAI = 'funai';
    case GEJSP = 'gejsp';
    case GEJSPC = 'gejspc';
    case GEJUSPC = 'gejuspc';
    case GESP = 'gesp';
    case GOVGO = 'govgo';
    case ICLA = 'icla';
    case ICP = 'icp';
    case IDAMP = 'idamp';
    case IFP = 'ifp';
    case IGP = 'igp';
    case IIACM = 'iiacm';
    case IICC = 'iicc';
    case IICCECF = 'iiccecf';
    case IICM = 'iicm';
    case IIGP = 'iigp';
    case IIJDM = 'iijdm';
    case IIPC = 'iipc';
    case IIPM = 'iipm';
    case IIRGD = 'iirgd';
    case IIRHM = 'iirhm';
    case IITB = 'iitb';
    case IML = 'iml';
    case INI = 'ini';
    case IPF = 'ipf';
    case ITCP = 'itcp';
    case ITEP = 'itep';
    case MAER = 'maer';
    case MB = 'mb';
    case MD = 'md';
    case MDS = 'mds';
    case MEC = 'mec';
    case MEX = 'mex';
    case MINDEF = 'mindef';
    case MJ = 'mj';
    case MM = 'mm';
    case MMA = 'mma';
    case MPAS = 'mpas';
    case MPE = 'mpe';
    case MPF = 'mpf';
    case MPT = 'mpt';
    case MRE = 'mre';
    case MT = 'mt';
    case MTE = 'mte';
    case MTPS = 'mtps';
    case NUMIG = 'numig';
    case OAB = 'oab';
    case OMB = 'omb';
    case PC = 'pc';
    case PF = 'pf';
    case PGFN = 'pgfn';
    case PM = 'pm';
    case POLITEC = 'politec';
    case PRF = 'prf';
    case PTC = 'ptc';
    case SCC = 'scc';
    case SCJDS = 'scjds';
    case SDS = 'sds';
    case SECC = 'secc';
    case SECCDE = 'seccde';
    case SEDS = 'seds';
    case SEGUP = 'segup';
    case SEJSP = 'sejsp';
    case SEJUC = 'sejuc';
    case SEJUSP = 'sejusp';
    case SEPC = 'sepc';
    case SEPOL = 'sepol';
    case SES = 'ses';
    case SESC = 'sesc';
    case SESDC = 'sesdc';
    case SESDEC = 'sesdec';
    case SESEG = 'seseg';
    case SESP = 'sesp';
    case SESPAP = 'sespap';
    case SESPDC = 'sespdc';
    case SESPDS = 'sespds';
    case SGPC = 'sgpc';
    case SGPJ = 'sgpj';
    case SIM = 'sim';
    case SJ = 'sj';
    case SJCDH = 'sjcdh';
    case SJDS = 'sjds';
    case SJS = 'sjs';
    case SJTC = 'sjtc';
    case SJTS = 'sjts';
    case SNJ = 'snj';
    case SPMAF = 'spmaf';
    case SPTC = 'sptc';
    case SRDPF = 'srdpf';
    case SRF = 'srf';
    case SRTE = 'srte';
    case SSDC = 'ssdc';
    case SSDS = 'ssds';
    case SSI = 'ssi';
    case SSP = 'ssp';
    case SSPCGP = 'sspcgp';
    case SSPDC = 'sspdc';
    case SSPDS = 'sspds';
    case SSPPC = 'ssppc';
    case SUSEP = 'susep';
    case SUSEPE = 'susepe';
    case TJ = 'tj';
    case TJAEM = 'tjaem';
    case TRE = 'tre';
    case TRF = 'trf';
    case TSE = 'tse';

    public function getLabel(): string
    {
        return match ($this) {
            self::ABNC => 'Academia Brasileira de Neurocirurgia',
            self::AGU => 'Advocacia Geral da União',
            self::ANAC => 'Agência Nacional de Aviação Civil',
            self::CAER => 'Clube de Aeronáutica',
            self::CAU => 'Conselho de Arquitetura e Urbanismo',
            self::CBM => 'Corpo de Bombeiros Militar',
            self::CFA => 'Conselho Federal de Administração',
            self::CFB => 'Conselho Federal de Biblioteconomia',
            self::CFBIO => 'Conselho Federal de Biologia',
            self::CFBM => 'Conselho Federal de Biomedicina',
            self::CFC => 'Conselho Federal de Contabilidade',
            self::CFESS => 'Conselho Federal de Serviço Social',
            self::CFF => 'Conselho Federal de Farmácia',
            self::CFFA => 'Conselho Federal de Fonoaudiologia',
            self::CFM => 'Conselho Federal de Medicina',
            self::CFMV => 'Conselho Federal de Medicina Veterinária',
            self::CFN => 'Conselho Federal de Nutrição',
            self::CFO => 'Conselho Federal de Odontologia',
            self::CFP => 'Conselho Federal de Psicologia',
            self::CFQ => 'Conselho Federal de Química',
            self::CFT => 'Conselho Federal dos Técnicos Industriais',
            self::CFTA => 'Conselho Federal dos Técnicos Agrícolas',
            self::CGPI => 'Coordenação Geral de Privilégios e Imunidades',
            self::CGPMAF => 'Coordenadoria Geral de Polícia Marítima',
            self::CIPC => 'Centro de Inteligência da Polícia Civil',
            self::CNIG => 'Conselho Nacional de Imigração',
            self::CNT => 'Confederação Nacional do Transporte',
            self::CNTV => 'Confederação Nacional de Vigilantes e Prestadores de Serviços',
            self::COFECI => 'Conselho Federal de Corretores de Imóveis',
            self::COFECON => 'Conselho Federal de Economia',
            self::COFEM => 'Conselho Federal de Museologia',
            self::COFEN => 'Conselho Federal de Enfermagem',
            self::COFFITO => 'Conselho Regional de Fisioterapia e Terapia Ocupacional',
            self::COMAER => 'Comando da Aeronáutica',
            self::CONFE => 'Conselho Federal de Estatística',
            self::CONFEA => 'Conselho Federal de Engenharia e Agronomia',
            self::CONFEF => 'Conselho Federal de Educação Física',
            self::CONFERE => 'Conselho Federal dos Representantes Comerciais',
            self::CONRE => 'Conselho Regional de Estatística',
            self::CONRERP => 'Conselho Regional de Profissionais de Relações Públicas',
            self::CORE => 'Conselho Regional dos Representantes Comerciais',
            self::CORECON => 'Conselho Regional de Economia',
            self::COREM => 'Conselho Regional de Museologia',
            self::COREN => 'Conselho Regional de Enfermagem',
            self::CRA => 'Conselho Regional de Administração',
            self::CRAS => 'Centro de Referência de Assistência Social',
            self::CRB => 'Conselho Regional de Biblioteconomia',
            self::CRBIO => 'Conselho Regional de Biologia',
            self::CRBM => 'Conselho Regional de Biomedicina',
            self::CRC => 'Conselho Regional de Contabilidade',
            self::CREA => 'Conselho Regional de Engenharia e Agronomia',
            self::CRECI => 'Conselho Regional de Corretores de Imóveis',
            self::CREF => 'Conselho Regional de Educação Física',
            self::CREFITO => 'Conselho Regional de Fisioterapia e Terapia Ocupacional',
            self::CRESS => 'Conselho Regional de Serviço Social',
            self::CRF => 'Conselho Regional de Farmácia',
            self::CRFA => 'Conselho Regional de Fonoaudiologia',
            self::CRM => 'Conselho Regional de Medicina',
            self::CRMV => 'Conselho Regional de Medicina Veterinária',
            self::CRN => 'Conselho Regional de Nutrição',
            self::CRO => 'Conselho Regional de Odontologia',
            self::CRP => 'Conselho Regional de Psicologia',
            self::CRPRE => 'Conselho Regional de Profissionais de Relações Públicas',
            self::CRQ => 'Conselho Regional de Química',
            self::CRT => 'Conselho Regional dos Técnicos Industriais',
            self::CRTA => 'Conselho Regional de Técnicos de Administração',
            self::CTPS => 'Carteira de Trabalho e Previdência Social',
            self::CV => 'Cartório Civil',
            self::DELEMIG => 'Delegacia de Polícia de Imigração',
            self::DETRAN => 'Departamento Estadual de Trânsito',
            self::DGPC => 'Diretoria Geral da Polícia Civil',
            self::DIC => 'Diretoria de Identificação Civil',
            self::DICC => 'Diretoria de Identificação Civil e Criminal',
            self::DIREX => 'Diretoria Executiva',
            self::DPF => 'Departamento de Polícia Federal',
            self::DPMAF => 'Divisão de Polícia Marítima, Aérea e de Fronteiras',
            self::DPT => 'Departamento de Polícia Técnica Geral',
            self::DPTC => 'Departamento de Polícia Técnico-Científica',
            self::DREX => 'Delegacia Regional Executiva',
            self::DRT => 'Delegacia Regional do Trabalho',
            self::EB => 'Exército Brasileiro',
            self::FAB => 'Força Aérea Brasileira',
            self::FENAJ => 'Federação Nacional dos Jornalistas',
            self::FGTS => 'Fundo de Garantia do Tempo de Serviço',
            self::FIPE => 'Fundação Instituto de Pesquisas Econômicas',
            self::FLS => 'Fundação Lyndolpho Silva',
            self::FUNAI => 'Fundação Nacional do Índio',
            self::GEJSP => 'Gerência de Estado de Justiça, Segurança Pública e Cidadania',
            self::GEJSPC => 'Gerência de Estado de Justiça, Segurança Pública e Cidadania',
            self::GEJUSPC => 'Gerência de Estado de Justiça, Segurança Pública e Cidadania',
            self::GESP => 'Gerência de Estado de Segurança Pública',
            self::GOVGO => 'Governo do Estado de Goiás',
            self::ICLA => 'Carteira de identidade Classista',
            self::ICP => 'Instituto de Polícia Científica',
            self::IDAMP => 'Instituto de Identificação Dr. Aroldo Mendes Paiva',
            self::IFP => 'Instituto Félix Pacheco',
            self::IGP => 'Instituto Geral de Perícias',
            self::IIACM => 'Instituto de Identificação Aderson Conceição de Melo',
            self::IICC => 'Instituto de Identificação Civil e Criminal',
            self::IICCECF => 'Instituto de Identificação Civil e Criminal Engrácia da Costa Francisco',
            self::IICM => 'Instituto de Identificação Carlos Menezes',
            self::IIGP => 'Instituto de Identificação Gonçalo Pereira',
            self::IIJDM => 'Instituto de Identificação João de Deus Martins',
            self::IIRGD => 'Instituto de Identificação Ricardo Gumbleton Daunt',
            self::IIPC => 'Instituto de Identificação da Polícia Civil',
            self::IIPM => 'Instituto de Identificação Pedro Mello',
            self::IIRGD => 'Instituto de Identificação Ricardo Gumbleton Daunt',
            self::IIRHM => 'Instituto de Identificação Raimundo Hermínio de Melo',
            self::IITB => 'Instituto de Identificação Tavares Buril',
            self::IML => 'Instituto Médico-Legal',
            self::INI => 'Instituto Nacional de Identificação',
            self::IPF => 'Instituto Pereira Faustino',
            self::ITCP => 'Instituto Técnico-Científico de Perícia',
            self::ITEP => 'Instituto Técnico-Científico de Perícia',
            self::MAER => 'Ministério da Aeronáutica',
            self::MB => 'Marinha do Brasil',
            self::MD => 'Ministério da Defesa',
            self::MDS => 'Ministério da Cidadania',
            self::MEC => 'Ministério da Educação e Cultura',
            self::MEX => 'Ministério do Exército',
            self::MINDEF => 'Ministério da Defesa',
            self::MJ => 'Ministério da Justiça',
            self::MM => 'Ministério da Marinha',
            self::MMA => 'Ministério da Marinha',
            self::MPAS => 'Ministério da Previdência e Assistência Social',
            self::MPE => 'Ministério Público Estadual',
            self::MPF => 'Ministério Público Federal',
            self::MPT => 'Ministério Público do Trabalho',
            self::MRE => 'Ministério das Relações Exteriores',
            self::MT => 'Ministério do Trabalho',
            self::MTE => 'Ministério da Economia',
            self::MTPS => 'Ministério do Trabalho e Previdência Social',
            self::NUMIG => 'Núcleo de Polícia de Imigração',
            self::OAB => 'Ordem dos Advogados do Brasil',
            self::OMB => 'Ordem dos Músicos do Brasil',
            self::PC => 'Polícia Civil',
            self::PF => 'Polícia Federal',
            self::PGFN => 'Procuradoria Geral da Fazenda Nacional',
            self::PM => 'Polícia Militar',
            self::POLITEC => 'Perícia Oficial e Identificação Técnica',
            self::PRF => 'Polícia Rodoviária Federal',
            self::PTC => 'Polícia Técnico-Científica',
            self::SCC => 'Secretaria de Estado da Casa Civil',
            self::SCJDS => 'Secretaria Coordenadora de Justiça e Defesa Social',
            self::SDS => 'Secretaria de Defesa Social',
            self::SECC => 'Secretaria de Estado da Casa Civil',
            self::SECCDE => 'Secretaria de Estado da Casa Civil e Desenvolvimento Econômico',
            self::SEDS => 'Secretaria de Estado da Defesa Social',
            self::SEGUP => 'Secretaria de Estado da Segurança Pública e da Defesa Social',
            self::SEJSP => 'Secretaria de Estado de Justiça e Segurança Pública',
            self::SEJUC => 'Secretaria de Estado da Justiça',
            self::SEJUSP => 'Secretaria de Estado de Justiça e Segurança Pública',
            self::SEPC => 'Secretaria de Estado da Polícia Civil',
            self::SEPOL => 'Secretaria de Estado de Polícia Civil',
            self::SES => 'Secretaria de Estado da Segurança',
            self::SESC => 'Secretaria de Estado da Segurança e Cidadania',
            self::SESDC => 'Secretaria de Estado da Segurança, Defesa e Cidadania',
            self::SESDEC => 'Secretaria de Estado da Segurança, Defesa e Cidadania',
            self::SESEG => 'Secretaria Estadual de Segurança',
            self::SESP => 'Secretaria de Estado da Segurança Pública',
            self::SESPAP => 'Secretaria de Estado da Segurança Pública e Administração Penitenciária',
            self::SESPDC => 'Secretaria de Estado de Segurança Pública e Defesa do Cidadão',
            self::SESPDS => 'Secretaria de Estado de Segurança Pública e Defesa Social',
            self::SGPC => 'Superintendência Geral de Polícia Civil',
            self::SGPJ => 'Superintendência Geral de Polícia Judiciária',
            self::SIM => 'Serviço de Identificação da Marinha',
            self::SJ => 'Secretaria da Justiça',
            self::SJCDH => 'Secretaria da Justiça e dos Direitos Humanos',
            self::SJDS => 'Secretaria Coordenadora de Justiça e Defesa Social',
            self::SJS => 'Secretaria da Justiça e Segurança',
            self::SJTC => 'Secretaria da Justiça do Trabalho e Cidadania',
            self::SJTS => 'Secretaria da Justiça do Trabalho e Segurança',
            self::SNJ => 'Secretaria Nacional de Justiça / Departamento de Estrangeiros',
            self::SPMAF => 'Serviço de Polícia Marítima, Aérea e de Fronteiras',
            self::SPTC => 'Secretaria de Polícia Técnico-Científica',
            self::SRDPF => 'Superintendência Regional do Departamento de Polícia Federal',
            self::SRF => 'Receita Federal',
            self::SRTE => 'Superintendência Regional do Trabalho',
            self::SSDC => 'Secretaria da Segurança, Defesa e Cidadania',
            self::SSDS => 'Secretaria da Segurança e da Defesa Social',
            self::SSI => 'Secretaria de Segurança e Informações',
            self::SSP => 'Secretaria de Segurança Pública',
            self::SSPCGP => 'Secretaria de Segurança Pública e Coordenadoria Geral de Perícias',
            self::SSPDC => 'Secretaria de Segurança Pública e Defesa do Cidadão',
            self::SSPDS => 'Secretaria de Segurança Pública e Defesa Social',
            self::SSPPC => 'Secretaria de Segurança Pública Polícia Civil',
            self::SUSEP => 'Superintendência de Seguros Privados',
            self::SUSEPE => 'Superintendência dos Serviços Penitenciários',
            self::TJ => 'Tribunal de Justiça',
            self::TJAEM => 'Tribunal Arbitral e Mediação dos Estados Brasileiros',
            self::TRE => 'Tribunal Regional Eleitoral',
            self::TRF => 'Tribunal Regional Federal',
            self::TSE => 'Tribunal Superior Eleitoral',
        };
    }
}
